Repository witseie-elen4010/2022-group-lab-003, pull requests merged in 2022-06, with the labels that each got.

#49 Issue#23
  index.js
  package-lock.json
  public/scripts/login.js
  public/stylesheets/style.css
  routes/mainRoutes.js
  routes/paths.js
  views/about.html
  views/game.html
  views/instructions.html
  views/login.html
  views/options.html
Labels: enhancement, user-story, front-end-development

#52 [AUTOMATED TEST] The instructions page shows up after clicking the in…
  __tests__/instructions.page.js
  package-lock.json
  package.json
Labels: user-story

#54 Update colours #30
  public/scripts/main.js
  views/game.html
  views/instructions.html
  views/login.html
  views/options.html
Labels: enhancement, user-story

#50 [AUTOMATED TEST] The name of the game is on the login, options and g…
  package-lock.json
  tests/login.test.js
Labels: user-story

#53 [AUTOMATED TEST] The About page shows up after clicking the About but…
  package-lock.json
  tests/about.test.js
Labels: user-story

#51 [AUTOMATED TEST] The keyboard is displayed on the screen for the user…
  package-lock.json
  package.json
  tests/game.test.js
Labels: user-story, front-end-development

#57 #30 keyboard colour change
  public/scripts/main.js
Labels: enhancement, front-end-development

#55 [AUTOMATED TESTS] Test for board display on the screen
  tests/game.test.js
Labels: user-story

#56 [AUTOMATED TESTS] Checking the keyboard functionality and that it correctly updates the game board
  tests/keyboard.test.js
Labels: developer-sized-story, user-story

#59 Allowing for physical keyboard inputs #58
  public/scripts/main.js
Labels: enhancement, user-story

#61 [BUG] Fixing the bug that allows user to go to next row even if the w…
  public/scripts/main.js
Labels: bug, user-story

#62 [AUTOMATED TESTS] Test if requirements for login are met
  tests/login.test.js
Labels: developer-sized-story

#63 [AUTOMATED TESTS] Word tests
  tests/words.test.js
Labels: user-story

#65 [AUTOMATED TESTS] Test game board and keyboard colour changes after pressing enter
  public/scripts/main.js
  tests/boardColour.test.js
Labels: developer-sized-story

#64 Issue23
  database/db.js
  database/tables/loginDB.sql
  index.js
  package-lock.json
  package.json
  public/scripts/login.js
  public/stylesheets/style.css
  routes/mainRoutes.js
  routes/paths.js
  views/login.html
Labels: bug, enhancement, user-story

#66 Multiplayer Game
  database/checkdb.js
  database/tables/dataBaseTable.sql
  index.js
  package-lock.json
  package.json
  public/scripts/multiplayer.js
  public/stylesheets/style.css
  routes/mainRoutes.js
  views/login.html
  views/multiplayer.html
  views/options.html
Labels: enhancement, user-story

#68 Issue#31
  index.js
  public/scripts/multiplayer.js
Labels: enhancement, developer-sized-story, user-story

#75 Issue#72
  index.js
  public/scripts/multiplayer2.js
  routes/mainRoutes.js
  routes/paths.js
  views/multiplayer2.html
  views/options.html
Labels: enhancement, developer-sized-story, user-story

#76 Adding player moves/words to a database
  index.js
  package-lock.json
  package.json
  public/scripts/main.js
  views/game.html
Labels: enhancement, developer-sized-story, user-story
