Repository witseie-elen4010/2022-group-lab-003, pull requests merged in 2022-05, with the labels that each got.

#13 Keyboard display #3
  public/stylesheets/style.css
  views/game.html
Labels: user-story

#14 wordle-board display #5
  public/stylesheets/style.css
  views/game.html
  views/main.js
Labels: user-story

#18 Randomly choosing a word from a list of words #12
  views/main.js
Labels: developer-sized-story, user-story

#19 check input length #12
  views/main.js
Labels: developer-sized-story

#20 check if word in list #8
  views/main.js
Labels: developer-sized-story

#21 #9 game outcome
  views/main.js
Labels: user-story, front-end-development

#40 hyperlink for instructions #28
  public/stylesheets/style.css
  views/game.html
  views/instructions.html
Labels: enhancement, user-story, front-end-development

#42 Adding an extended word list #25
  public/scripts/Wordlist.js
  public/scripts/main.js
Labels: enhancement, developer-sized-story, user-story

#44 Redo of #issue25 due to merge conflicts
  public/scripts/Wordlist.js
  public/scripts/main.js
Labels: enhancement, developer-sized-story, user-story

#46 Fixing bug for issue#26
  public/scripts/main.js
Labels: bug
